Repository Kanaries/graphic-walker, pull requests merged in 2023-08, with the labels that each got.

#107 feat: add background&independence control
  packages/graphic-walker/src/components/toggle.tsx
  packages/graphic-walker/src/components/visualConfig/index.tsx
  packages/graphic-walker/src/config.ts
  packages/graphic-walker/src/interfaces.ts
  packages/graphic-walker/src/locales/en-US.json
  packages/graphic-walker/src/locales/ja-JP.json
  packages/graphic-walker/src/locales/zh-CN.json
  packages/graphic-walker/src/renderer/specRenderer.tsx
  packages/graphic-walker/src/store/visualSpecStore.ts
  packages/graphic-walker/src/vis/react-vega.tsx
Labels: P1

#134 feat: add computation mode
  README.md
  computation.md
  packages/graphic-walker/src/App.tsx
  packages/graphic-walker/src/components/dataTable/index.tsx
  packages/graphic-walker/src/components/pivotTable/store.tsx
  packages/graphic-walker/src/computation/clientComputation.ts
  packages/graphic-walker/src/computation/serverComputation.ts
  packages/graphic-walker/src/dataSource/datasetConfig/index.tsx
  packages/graphic-walker/src/dataSource/table.tsx
  packages/graphic-walker/src/fields/filterField/filterEditDialog.tsx
  packages/graphic-walker/src/fields/filterField/tabs.tsx
  packages/graphic-walker/src/index.tsx
  packages/graphic-walker/src/interfaces.ts
  packages/graphic-walker/src/lib/execExp.ts
  packages/graphic-walker/src/lib/interfaces.ts
  packages/graphic-walker/src/lib/op/aggregate.ts
  packages/graphic-walker/src/lib/viewQuery.ts
  packages/graphic-walker/src/renderer/hooks.ts
  packages/graphic-walker/src/renderer/index.tsx
  packages/graphic-walker/src/renderer/pureRenderer.tsx
  packages/graphic-walker/src/renderer/specRenderer.tsx
  packages/graphic-walker/src/services.ts
  packages/graphic-walker/src/store/commonStore.ts
  packages/graphic-walker/src/store/visualSpecStore.ts
  packages/graphic-walker/src/utils/save.ts
  packages/graphic-walker/src/utils/workflow.ts
  packages/graphic-walker/src/vis/react-vega.tsx
  packages/graphic-walker/src/visualSettings/index.tsx
  packages/graphic-walker/src/workers/filter.worker.js
  packages/graphic-walker/src/workers/sort.ts
  packages/graphic-walker/src/workers/sort.worker.ts
  packages/graphic-walker/src/workers/transform.ts
  packages/graphic-walker/src/workers/transform.worker.js
  packages/graphic-walker/src/workers/viewQuery.worker.js
Labels: enhancement

#94 feat: leaflet geojson support
  packages/graphic-walker/package.json
  packages/graphic-walker/src/App.tsx
  packages/graphic-walker/src/components/leafletRenderer/ChoroplethRenderer.tsx
  packages/graphic-walker/src/components/leafletRenderer/POIRenderer.tsx
  packages/graphic-walker/src/components/leafletRenderer/encodings.ts
  packages/graphic-walker/src/components/leafletRenderer/geoConfigPanel.tsx
  packages/graphic-walker/src/components/leafletRenderer/index.tsx
  packages/graphic-walker/src/components/leafletRenderer/tooltip.tsx
  packages/graphic-walker/src/components/leafletRenderer/utils.ts
  packages/graphic-walker/src/components/visualConfig/index.tsx
  packages/graphic-walker/src/config.ts
  packages/graphic-walker/src/fields/aestheticFields.tsx
  packages/graphic-walker/src/fields/fieldsContext.tsx
  packages/graphic-walker/src/fields/posFields/index.tsx
  packages/graphic-walker/src/interfaces.ts
  packages/graphic-walker/src/locales/en-US.json
  packages/graphic-walker/src/locales/ja-JP.json
  packages/graphic-walker/src/locales/zh-CN.json
  packages/graphic-walker/src/renderer/index.tsx
  packages/graphic-walker/src/renderer/pureRenderer.tsx
  packages/graphic-walker/src/renderer/specRenderer.tsx
  packages/graphic-walker/src/shadow-dom.tsx
  packages/graphic-walker/src/store/commonStore.ts
  packages/graphic-walker/src/store/visualSpecStore.ts
  packages/graphic-walker/src/utils/save.ts
  packages/graphic-walker/src/visualSettings/index.tsx
  yarn.lock
Labels: enhancement, P1

#86 Feat: collapsible table header
  packages/graphic-walker/src/components/pivotTable/index.tsx
  packages/graphic-walker/src/components/pivotTable/inteface.ts
  packages/graphic-walker/src/components/pivotTable/leftTree.tsx
  packages/graphic-walker/src/components/pivotTable/metricTable.tsx
  packages/graphic-walker/src/components/pivotTable/topTree.tsx
  packages/graphic-walker/src/components/pivotTable/utils.ts
  packages/graphic-walker/src/interfaces.ts
  packages/graphic-walker/src/locales/en-US.json
  packages/graphic-walker/src/locales/ja-JP.json
  packages/graphic-walker/src/locales/zh-CN.json
  packages/graphic-walker/src/renderer/index.tsx
  packages/graphic-walker/src/renderer/pureRenderer.tsx
  packages/graphic-walker/src/renderer/specRenderer.tsx
  packages/graphic-walker/src/services.ts
  packages/graphic-walker/src/store/commonStore.ts
  packages/graphic-walker/src/store/visualSpecStore.ts
  packages/graphic-walker/src/utils/save.ts
  packages/graphic-walker/src/visualSettings/index.tsx
  packages/graphic-walker/src/workers/buildMetricTable.worker.js
  packages/graphic-walker/src/workers/buildPivotTable.ts
Labels: P1

#125 [Feat] datetime drill down/up
  packages/graphic-walker/src/components/actionMenu/a11y.tsx
  packages/graphic-walker/src/components/actionMenu/index.tsx
  packages/graphic-walker/src/components/actionMenu/list.tsx
  packages/graphic-walker/src/constants.ts
  packages/graphic-walker/src/fields/datasetFields/dimFields.tsx
  packages/graphic-walker/src/fields/datasetFields/fieldPill.tsx
  packages/graphic-walker/src/fields/datasetFields/meaFields.tsx
  packages/graphic-walker/src/fields/datasetFields/utils.ts
  packages/graphic-walker/src/interfaces.ts
  packages/graphic-walker/src/lib/execExp.ts
  packages/graphic-walker/src/lib/op/dateTimeDrill.ts
  packages/graphic-walker/src/locales/en-US.json
  packages/graphic-walker/src/locales/ja-JP.json
  packages/graphic-walker/src/locales/zh-CN.json
  packages/graphic-walker/src/store/visualSpecStore.ts
Labels: P1

#140 wip: explain data
  packages/graphic-walker/src/App.tsx
  packages/graphic-walker/src/components/explainData/index.tsx
  packages/graphic-walker/src/lib/insights/explainBySelection.ts
  packages/graphic-walker/src/renderer/index.tsx
  packages/graphic-walker/src/store/commonStore.ts
  packages/graphic-walker/src/utils/normalization.ts
Labels: P1
